### PR TITLE
example desktop video scrubber using linear selector

### PR DESCRIPTION
**Pull request by joeyo**
I wanted to scrub through videos without needing to use jupyter/ipywidgets and figured out a way to do it using a `linear_selector`. Adding as an example in case it's useful.

### CODE REVIEW

**Comment by kushalkolar** [comment]
Thanks for the example! This will put a linear selector on top of the image.

We want to have in-canvas UI elements eventually, I'm planning to get started on this soon unless someone wants to try it out. See https://github.com/pyimgui/pyimgui/issues/336

**Comment by kushalkolar** [comment]
You could also embed it in a Qt app and use Qt for your UI.

**Comment by joeyo** [comment]
> You could also embed it in a Qt app and use Qt for your UI.

I actually initially started going down that route but could not get FPL master to work with PyQT/PySide at all.

**Comment by kushalkolar** [comment]
What errors were you getting, happy to take a look if you post an issue. I
think the Qt canvas is just a QWidget. You can also force the Qt canvas by
doing `plot = Plot(canvas="Qt")`. Wgpu sometimes selects glfw by default, I
think they fixed it recently.

**Comment by joeyo** [comment]
Okay, following-up here: https://github.com/fastplotlib/fastplotlib/issues/340

**Pull request closed without merging**
