### PR TITLE
Image widget

### PR DESCRIPTION
**Pull request by almarklein**
Just a small example to show the image widget on desktop. 

image

### CODE REVIEW

**Comment by almarklein** [comment]
BTW, there are a lot of files that get touched when I run black. What is the policy related to formatting and linting?

**Comment by almarklein** [comment]
> For this example, I think it'd be useful to add a note that if you want sliders to scroll through one or two dimensions you should use the ImageWidget in either Qt or jupyter. Since we don't have within canvas UI right now.

👍 

Odd though, because I have PySide6 installed, and it selects glfw. Will have a look why this is.

**Comment by almarklein** [comment]
Oh, it only looks for PyQt6 for now. Ref #384

**Comment by kushalkolar** [comment]
> Oh, it only looks for PyQt6 for now. Ref #384 

Yup! I updated that issue with the specifics.

**Comment by almarklein** [comment]
Backend selection is a bit iffy. Will still select glfw because wgou prefers it over qt. Something for another PR :)

**Comment by kushalkolar** [comment]
Yup I think that's why our Qt example explicitly chooses the canvas.

**Comment by kushalkolar** [comment]
Yup I think that's why our Qt example explicitly chooses the canvas

**Comment by kushalkolar** [comment]
If this is good to go you can mark it as ready for review to trigger the CI to run, and then copy the new screenshot from the regenerate action to the corresponding examples dir.

**Comment by almarklein** [comment]
> CI: `AttributeError: module 'fastplotlib' has no attribute 'widgets'`

But when I `import fastplotlib as flp` I can use `flp.widgets`. Which behavior is to be expected? :)

**Comment by kushalkolar** [comment]
ImageWidget is intended to be used from top level, i.e. fpl.ImageWidget. Not entirely sure how this is happening.

**Comment by almarklein** [comment]
This is. Perhaps at some point the ImageWidget relied on ipywidgets?

https://github.com/fastplotlib/fastplotlib/blob/97dd7581598e08d2320c1a208737164be2cdbdb7/fastplotlib/__init__.py#L11-L16

**Comment by kushalkolar** [comment]
> This is. Perhaps at some point the ImageWidget relied on ipywidgets?
> 
> https://github.com/fastplotlib/fastplotlib/blob/97dd7581598e08d2320c1a208737164be2cdbdb7/fastplotlib/__init__.py#L11-L16

Ah yes good catch! That shouldn't be there.

**Pull request merged**
