### PR TITLE
fix typo in the requested limit name of the wgpu device

### PR DESCRIPTION
**Pull request by jcafhe**
Hi,

when running different examples involving images, the following exception is raised:

```python
Traceback (most recent call last):
  File "***\fastplotlib\examples\gridplot\gridplot_non_square.py", line 20, in <module>
    figure[0, 0].add_image(data=im)
  File "***\fastplotlib\fastplotlib\layouts\_graphic_methods_mixin.py", line 75, in add_image
    return self._create_graphic(
           ^^^^^^^^^^^^^^^^^^^^^
  File "***\fastplotlib\fastplotlib\layouts\_graphic_methods_mixin.py", line 24, in _create_graphic
    graphic = graphic_class(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\fastplotlib\fastplotlib\graphics\image.py", line 126, in __init__
    self._data = TextureArray(data, isolated_buffer=isolated_buffer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\fastplotlib\fastplotlib\graphics\_features\_image.py", line 24, in __init__
    self._texture_limit_2d = shared.device.limits["max-texture-dimension2d"]
                             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'max-texture-dimension2d'
```

It fails for the following examples (non-exhaustive list), on windows10, python 3.12.6, pygfx 0.6.0, wgpu 0.19.1 (can't test right now on linux because of an error related to imgui):
- example/gridplot/*
- heatmap/heatmap.py
- image/*

I believe there's a typo in the string passed to the `limits` property of the `wgpu.Device` object. From the wgpu documentation (Rust), the constant is named 'max_texture_dimension_2d', at least since wgpu-0.10.1:
https://docs.rs/wgpu/latest/wgpu/struct.Limits.html#structfield.max_texture_dimension_2d

By appling the lower-case style, the examples now work by adding an hyphen before "2d". I don't know if it is specific to my setup, but this fix seems to be aligned with the wgpu API.

### CODE REVIEW

**Comment by kushalkolar** [comment]
Thanks! Looks like this change in wgpu is now in the release: https://github.com/pygfx/wgpu-py/pull/617

**Comment by jcafhe** [comment]
nice! This explains why there were no errors before. I didn't think to look at the issue tracker of pygfx.

**Comment by kushalkolar** [comment]
test failures are due to https://github.com/pygfx/wgpu-py/issues/644, need to wait for the next release of wgpu with https://github.com/pygfx/wgpu-py/pull/645

**Comment by kushalkolar** [comment]
If you can update the test as well it should be good to go! https://github.com/fastplotlib/fastplotlib/actions/runs/11975376261/job/33491202021?pr=679#step:8:24

**Comment by jcafhe** [comment]
That should be ok, all tests pass on my machine, with pygfx installed from its main branch, to be aligned with the CI setup :
` pip install git+https://github.com/pygfx/pygfx.git@main`.

**Comment by jcafhe** [comment]
Sorry, there are still some errors. I will investigate ...

**Comment by kushalkolar** [comment]
Looks like there are [no imgui wheels for python 3.10](https://pypi.org/project/imgui-bundle/#files) so it's trying to build [but it requires `libxrandr-dev`](https://github.com/fastplotlib/fastplotlib/actions/runs/12037747152/job/33562186459?pr=679#step:5:229), you can add it to the same place where all other apt packages are installed [here](https://github.com/fastplotlib/fastplotlib/blob/main/.github/workflows/ci.yml#L40-L43) and [here](https://github.com/fastplotlib/fastplotlib/blob/main/.github/workflows/ci.yml#L96-L99)

**Comment by jcafhe** [comment]
Thanks. I've added the installation of `xorg-dev` which should contain `libxrandr` for ubuntu, as suggested in [GLFW documentation](https://www.glfw.org/docs/3.3/compile.html).

**Comment by kushalkolar** [comment]
had to update the CI timeout, it takes longer since it has to build imgui 1.5.2 for python 3.10. Anyways this PR will fix all those issues: https://github.com/pygfx/wgpu-py/pull/649

**Comment by jcafhe** [comment]
ok, no problem, so we just have to wait I guess.

**Comment by kushalkolar** [comment]
I'm going to merge this into a temporary branch where we're updating things w.r.t. upstream changes like #686 where we're switching from pyav to ffmpeg.

**Pull request merged**
